const cosiness = [
	{ name: 'slide1', url: '/images/swiper-cosiness/1.webp' },
	{ name: 'slide2', url: '/images/swiper-cosiness/2.webp' },
	{ name: 'slide3', url: '/images/swiper-cosiness/3.webp' },
	{ name: 'slide4', url: '/images/swiper-cosiness/4.webp' },
	{ name: 'slide5', url: '/images/swiper-cosiness/5.webp' },
	{ name: 'slide6', url: '/images/swiper-cosiness/6.webp' },
	{ name: 'slide7', url: '/images/swiper-cosiness/7.webp' },
	{ name: 'slide8', url: '/images/swiper-cosiness/8.webp' },
	{ name: 'slide9', url: '/images/swiper-cosiness/9.webp' },
	{ name: 'slide10', url: '/images/swiper-cosiness/10.webp' },
	{ name: 'slide11', url: '/images/swiper-cosiness/11.webp' },
	{ name: 'slide12', url: '/images/swiper-cosiness/12.webp' },
	{ name: 'slide13', url: '/images/swiper-cosiness/13.webp' },
	{ name: 'slide14', url: '/images/swiper-cosiness/14.webp' },
	{ name: 'slide15', url: '/images/swiper-cosiness/15.webp' },
	{ name: 'slide16', url: '/images/swiper-cosiness/16.webp' },
	{ name: 'slide17', url: '/images/swiper-cosiness/17.webp' },
	{ name: 'slide18', url: '/images/swiper-cosiness/18.webp' },
	{ name: 'slide19', url: '/images/swiper-cosiness/19.webp' },
	{ name: 'slide20', url: '/images/swiper-cosiness/20.webp' },
	{ name: 'slide21', url: '/images/swiper-cosiness/21.webp' },
	{ name: 'slide22', url: '/images/swiper-cosiness/22.webp' },
	{ name: 'slide23', url: '/images/swiper-cosiness/23.webp' },
]

export default cosiness
